name: CI Tricount

on:
  push:
    paths:
      - 'TriCount/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: build
        run: ./gradlew clean build

      - name: make zip
        run: zip -qq -r ./tricount.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ./tricount.zip s3://tricount-bucket/tricount.zip

      - name: Code deploy
        run: aws deploy create-deployment --application-name tricount-codeDeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name group1
          --s3-location bucket=tricount-bucket,bundleType=zip,key=tricount.zip


